# Basic test: install the dependencies, start the app, and make a basic request.

name: Dashboard Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      hub:
        image: selenium/hub
      chrome:
        image: selenium/node-chrome
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-test.txt
        python -m pip install pytest

    # This would be a good place to add flake8 / Black
    # - name: Lint
    #  runs-on: ubuntu-latest
    #  needs: build

    - name: Dash tests (Webdriver)
      run: |
        pytest --headless

